### ISSUE TITLE
I want to translate this mod into Chinese

### ISSUE THREAD

**Issue by EDTmagiclab** [Maxmani/touhou-origins#1]
I want to translate this mod into Chinese，can I do this?

**Comment by Maxmani** [comment]
Yes, feel free to translate the mod. I would really appreciate it.

**Comment by EDTmagiclab** [comment]
I finished the translation and posted it on GitHub

**Comment by Maxmani** [comment]
If you want to include it in the main build and create a pull request, I would gladly merge it.

**Comment by EDTmagiclab** [comment]
I have already create a pull request，you can merge it if you want
