### ISSUE TITLE
How to choose the upgrade path?

### ISSUE THREAD

**Issue by EDTmagiclab** [Maxmani/touhou-origins#10]
I can't find anyting about choose the upgrade path,for example,how to close the satori's eye

**Comment by wasakoki** [comment]
currently all upgrade paths can be done by having the upgrade item in your hand (string for closing satori's eye) and then pressing and holding down the use key for 5 seconds (the right mouse button by default).

**Comment by EDTmagiclab** [comment]
> currently all upgrade paths can be done by having the upgrade item in your hand (string for closing satori's eye) and then pressing and holding down the use key for 5 seconds (the right mouse button by default).

Thank you!
