### ISSUE TITLE
Potential packet overload issues with Apugli

### ISSUE THREAD

**Issue by ChrysanthCow** [Maxmani/touhou-origins#19]
Hey, so idk where else to write to you but I'm the developer of Apugli.

I'd recommend updating the mod to the latest version as I've optimised some very unoptimised packets of the mod.

Thanks for using my library btw. I think that's cool, also I'm a touhou fan.

**Comment by ChrysanthCow** [comment]
Quoted from https://github.com/Mos-Origins/GroundedOrigins/issues/16
> Basically one very unoptimised packet would trigger multiple times each tick for each individual value, in smaller settings this isn't noticeable but when you've got a larger entitybase, packet overload happens.

**Comment by Maxmani** [comment]
Will do, thanks for letting me know.
