### ISSUE TITLE
Can't build a mod

### ISSUE THREAD

**Issue by EDTmagiclab** [Maxmani/touhou-origins#20]
I'm trying to build the latest verison,but it can't work.And here is the crash report.
PS D:\touhouorigin-project\touhou-origins> gradle build
Starting a Gradle Daemon, 2 incompatible Daemons could not be reused, use --status for details

> Configure project :
Fabric Loom: 1.0.16
Found existing cache lock file, rebuilding loom cache. This may have been caused by a failed or canceled build.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'touhou-origins'.
> Could not resolve all dependencies for configuration ':modImplementation'.
   > Could not find com.github.DaFuqs:AdditionalEntityAttributes:95f13798d1.
     Searched in the following locations:
       - file:/D:/touhouorigin-project/touhou-origins/.gradle/loom-cache/remapped_mods/com/github/DaFuqs/AdditionalEntityAttributes/95f13798d1/AdditionalEntityAttributes-95f13798d1.pom
       - https://maven.fabricmc.net/com/github/DaFuqs/AdditionalEntityAttributes/95f13798d1/AdditionalEntityAttributes-95f13798d1.pom
       - https://libraries.minecraft.net/com/github/DaFuqs/AdditionalEntityAttributes/95f13798d1/AdditionalEntityAttributes-95f13798d1.pom
       - https://libraries.minecraft.net/com/github/DaFuqs/AdditionalEntityAttributes/95f13798d1/AdditionalEntityAttributes-95f13798d1.jar
       - https://repo.maven.apache.org/maven2/com/github/DaFuqs/AdditionalEntityAttributes/95f13798d1/AdditionalEntityAttributes-95f13798d1.pom
       - file:/D:/touhouorigin-project/gradle-7.6/jars/caches/fabric-loom/95f13798d1/AdditionalEntityAttributes.jar
       - file:/D:/touhouorigin-project/touhou-origins/.gradle/loom-cache/95f13798d1/AdditionalEntityAttributes.jar
       - https://ladysnake.jfrog.io/artifactory/mods/com/github/DaFuqs/AdditionalEntityAttributes/95f13798d1/AdditionalEntityAttributes-95f13798d1.pom
       - https://jitpack.io/com/github/DaFuqs/AdditionalEntityAttributes/95f13798d1/AdditionalEntityAttributes-95f13798d1.pom
       - https://maven.shedaniel.me/com/github/DaFuqs/AdditionalEntityAttributes/95f13798d1/AdditionalEntityAttributes-95f13798d1.pom
       - https://maven.terraformersmc.com/com/github/DaFuqs/AdditionalEntityAttributes/95f13798d1/AdditionalEntityAttributes-95f13798d1.pom
       - https://maven.merchantpug.net/releases/com/github/DaFuqs/AdditionalEntityAttributes/95f13798d1/AdditionalEntityAttributes-95f13798d1.pom
     Required by:
         project : > com.github.apace100:origins-fabric:v1.7.1 > com.github.apace100:apoli:624eb4d094

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 17s

**Comment by Maxmani** [comment]
Not an issue with the mod per se, but it's unable to download the dependency Origins needs. As a workaround, you can try putting the contents of [this](https://github.com/Maxmani/touhou-origins/files/10273676/DaFuqs.zip) inside of `touhou-origins/.gradle/loom-cache/remapped_mods/net_fabricmc_yarn_1_19_2_1_19_2_whatever_build_version_you_have/com/github`. If that doesn't work, try putting the required files wherever Gradle is looking for them. Other than that, I don't really know how to proceed except letting the [dev](https://github.com/DaFuqs/AdditionalEntityAttributes) know.

**Comment by EDTmagiclab** [comment]
OK， I‘ll try it
