### ISSUE TITLE
quilt crash with only touhou origins and dependencies, seems to be aplugi.

### ISSUE THREAD

**Issue by Lhruggles** [Maxmani/touhou-origins#22]
I am getting this crash, after removing aplugi and touhou origins the game will launch.

[crash-2023-01-29_02.09.31-client.txt](https://github.com/Maxmani/touhou-origins/files/10529328/crash-2023-01-29_02.09.31-client.txt)

**Comment by Lhruggles** [comment]
Seems to be a mixin injection failure, but I am not tech-savvy enough to tell for sure.

**Comment by Maxmani** [comment]
This was indeed caused by Apugli and it seems the crash has already been fixed, so I'll update the library on my end. Interestingly enough, the crash does not happen in the dev environment, so I completely missed it.

**Comment by Lhruggles** [comment]
Ah great, thanks!
