### ISSUE TITLE
Mod Incompatibility Issue with Simply Swords

### ISSUE THREAD

**Issue by Draconikal** [Maxmani/touhou-origins#28]
I have been setting up a custom mod pack on Minecraft 1.20.1, and found that the error; Invalid Player Data occurs on world creation when using the mod Simply Swords[Fabric and Forge], I had previously found that other mods to add Minecraft dungeons armor and weapons caused this issue as well, I am not sure that these are also incompatible but have a suspicion they may be.

**Comment by Maxmani** [comment]
Can't reproduce. Try using the mod with XL Packets or similar.
