### ISSUE TITLE
(unimportant) Bird bones are not light

### ISSUE THREAD

**Issue by Yay4** [Maxmani/touhou-origins#29]
Bird bones are denser than mammal bones the reason they are hollow is so they can have enough oxygen during long flights

**Comment by EDTmagiclab** [comment]
My biology teacher told me that bird has lighter bones so they can fly easier.If the armor is too heavy,they can't fly.And birds use air sac to get more oxygen during flights.

**Comment by Yay4** [comment]
well your biology teacher as wrong a quick google search can confirm that but you are correct with the armor and air sac parts
