### ISSUE TITLE
Suggestion ... Tweak how drowning and lava damage interacts with Immortals

### ISSUE THREAD

**Issue by MLMII** [Maxmani/touhou-origins#34]
I'm not sure if it's intended for lore reasons as I'm not familiar with the Touhou Project but drowning and lava damage doesn't seem to lower the divinity meter which allows an Immortal to stay underwater or in a lava pit for a very long time.

**Comment by Maxmani** [comment]
Divinity getting reduced from being hit requires an attacker. This was probably intended at the time, as it also goes down over time. It could also be an oversight, although I'm in the process of rewriting the entire mod, and Celestial is going to receive a heavy rework anyway.
