### ISSUE TITLE
Crashing on Startup (v0.7.1)

### ISSUE THREAD

**Issue by Kaede4Life** [Maxmani/touhou-origins#7]
Hello, my game crashes early on startup with this mod. It does not display a full crash report, but hopefully it is enough.

Log:
https://gist.github.com/Kaede4Life/53fe20ccdd0afc7ae049b1659adea241

**Comment by Dorrivix** [comment]
This is happening to me on the current release for 1.18.2 (touhouorigins-0.4.1-1.18.2)
[latest.log](https://github.com/Maxmani/touhou-origins/files/10052532/latest.log)

**Comment by Maxmani** [comment]
> This is happening to me on the current release for 1.18.2 (touhouorigins-0.4.1-1.18.2) [latest.log](https://github.com/Maxmani/touhou-origins/files/10052532/latest.log)

I've backported the fix to 1.18.2 now.
